server:
  port: ${PORT:8080}

spring:
  application:
    name: parking-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: user
    password: pass
  cloud:
    openfeign:
      client:
        config:
          company-branch-service:
            url: ${COMPANY_BRANCH_SERVICE_URL}
          employee-service:
            url: ${EMPLOYEE_SERVICE_URL}

application:
  enrichment-mode: ${ENRICHMENT_MODE:multi}
